version : "3"


volumes :

  maria-db-data :
    name        : maria-db-volumes
    driver      : local
    driver_opts:
      type     : none                                   #type = none means auto
      device   : /home/hdelmas/data/maria-db-data       #location on the host
      o        : bind                                   #o is for option

  wordpress-data :
    name        : wordpress-volumes
    driver      : local
    driver_opts:
      type     : none 
      device   : /home/hdelmas/data/wordpress-data       
      o        : bind       


services :

  inc-maria-db :
    build     : requirements/mariadb
    image     : inc-maria-db
    networks  : 
        - inception-network
    volumes   :
        - maria-db-data:/var/lib/mysql
    env_file  : .env
    restart   : always
  
  inc-nginx :
    build     : requirements/nginx
    image     : inc-nginx
    ports      :
        - "443:443"
    networks  : 
        - inception-network
    depends_on : 
        - inc-wordpress
    volumes   :
        - wordpress-data:/var/www/html
    env_file  : .env
    restart   : always

  inc-wordpress :
    build     : requirements/wordpress
    image     : inc-wordpress
    networks  : 
        - inception-network
    volumes   :
        - wordpress-data:/var/www/html
    depends_on : 
        - inc-maria-db
    env_file  : .env
    restart   : always


networks :

  inception-network :